---
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: restart php-fpm
  ansible.builtin.service:
    name: php7.4-fpm
    state: restarted

- name: restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: restart keydb
  ansible.builtin.service:
    name: keydb
    state: restarted

